<?php

$products = [
    [
        'id' => 1,
        'name' => 'NEeNbvdvaMbXeNCqvrL',
        'price' => 1045.83,
        'stars' => 5,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 2,
        'name' => 'NeypK',
        'price' => 684.70,
        'stars' => 1,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 3,
        'name' => 'xdIyPMrQwTwr',
        'price' => 1246.7,
        'stars' => 2,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 4,
        'name' => 'XSOZyCqqGKBUBUhtHpNW',
        'price' => 1470.25,
        'stars' => 4,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 5,
        'name' => 'SxwqZhzMx',
        'price' => 1173.39,
        'stars' => 0,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 6,
        'name' => 'XEowBjSygErWVkzFGAtl',
        'price' => 1491.13,
        'stars' => 0,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 7,
        'name' => 'gCDcghmTLaCR',
        'price' => 1159.17,
        'stars' => 1,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 8,
        'name' => 'wzjlpxEeaZ',
        'price' => 870.31,
        'stars' => 3,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 9,
        'name' => 'njaepgdHSBUaGWWE',
        'price' => 260.11,
        'stars' => 1,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 10,
        'name' => 'JRdJZBYswlKWidINP',
        'price' => 534.94,
        'stars' => 5,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 11,
        'name' => 'gsLzbqoTVVCfphjMBfk',
        'price' => 1431.90,
        'stars' => 3,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 12,
        'name' => 'lBsAeyijpGKgDFHcD',
        'price' => 146.48,
        'stars' => 0,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 13,
        'name' => 'xyDaAnzqYJERHTtrX',
        'price' => 635.24,
        'stars' => 3,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 14,
        'name' => 'mkYhDsQ',
        'price' => 906.90,
        'stars' => 5,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 15,
        'name' => 'GkoOukdiwtlPfZYlJ',
        'price' => 253.41,
        'stars' => 4,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 16,
        'name' => 'bNnZHyHcL',
        'price' => 86.18,
        'stars' => 2,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 17,
        'name' => 'XsdbiWtnPrpsr',
        'price' => 716.93,
        'stars' => 1,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 18,
        'name' => 'WjzmnZVwhbByP',
        'price' => 458.08,
        'stars' => 1,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 19,
        'name' => 'GXiHdxiVktI',
        'price' => 773.35,
        'stars' => 4,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 20,
        'name' => 'wDHZRrlQdRxjjaQ',
        'price' => 440.27,
        'stars' => 3,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 21,
        'name' => 'sZnCVcOTBAhMRWTOoGUp',
        'price' => 522.38,
        'stars' => 2,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 22,
        'name' => 'MjNcvryPksyQVXWddMIs',
        'price' => 157.60,
        'stars' => 2,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 23,
        'name' => 'elYzhbwLtt',
        'price' => 239.24,
        'stars' => 2,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 24,
        'name' => 'nTKiydFRWwwQ',
        'price' => 1121.97,
        'stars' => 1,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 25,
        'name' => 'OqLmbxYAbobex',
        'price' => 155.63,
        'stars' => 2,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 26,
        'name' => 'rVUwrPfbCuQXbBt',
        'price' => 392.64,
        'stars' => 5,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 27,
        'name' => 'GYFoBxmZwGwBcIQEJVq',
        'price' => 389.96,
        'stars' => 2,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 28,
        'name' => 'cdqFJvDyBdhDwu',
        'price' => 1353.80,
        'stars' => 2,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 29,
        'name' => 'SWhyjke',
        'price' => 1262.19,
        'stars' => 5,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 30,
        'name' => 'jCoYGDlSCcEVrQefs',
        'price' => 1460.69,
        'stars' => 0,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 31,
        'name' => 'wysFlnpLM',
        'price' => 325.52,
        'stars' => 2,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 32,
        'name' => 'erWJmgNOkJIar',
        'price' => 835.0,
        'stars' => 2,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 33,
        'name' => 'hXbHiwfpLsXQh',
        'price' => 98.5,
        'stars' => 5,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 34,
        'name' => 'nfjBH',
        'price' => 402.16,
        'stars' => 2,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 35,
        'name' => 'MVagLCLYmyZUs',
        'price' => 899.90,
        'stars' => 2,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 36,
        'name' => 'tNAus',
        'price' => 1369.2,
        'stars' => 0,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 37,
        'name' => 'BkdoMm',
        'price' => 837.26,
        'stars' => 0,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 38,
        'name' => 'SmGXNJ',
        'price' => 558.12,
        'stars' => 0,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 39,
        'name' => 'DUyOEZRXHPJeof',
        'price' => 915.82,
        'stars' => 3,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 40,
        'name' => 'YafoqSbObDZWTV',
        'price' => 260.45,
        'stars' => 4,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 41,
        'name' => 'GDIkSixZvtOy',
        'price' => 332.90,
        'stars' => 3,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 42,
        'name' => 'mYMMTnqfFzSK',
        'price' => 324.67,
        'stars' => 4,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 43,
        'name' => 'BFBBnruw',
        'price' => 1412.19,
        'stars' => 4,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 44,
        'name' => 'QvMRr',
        'price' => 951.,
        'stars' => 0,
        'discount' => 1,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 45,
        'name' => 'NLnHzcJdONDKTz',
        'price' => 395.88,
        'stars' => 0,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 46,
        'name' => 'CTAQdPKnQMdqIi',
        'price' => 628.34,
        'stars' => 1,
        'discount' => 0,
        'stock' => 0,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 47,
        'name' => 'gLUPtMbAR',
        'price' => 22.33,
        'stars' => 4,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 48,
        'name' => 'EeLUqNQUnBddbrDgFU',
        'price' => 163.39,
        'stars' => 4,
        'discount' => 0,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
    [
        'id' => 49,
        'name' => 'TLnpzMTSZJIJGufr',
        'price' => 1048.36,
        'stars' => 1,
        'discount' => 1,
        'stock' => 1,
        'image' => 'http://unsplash.it/300/180?random&gravity=center',
    ],
];
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
    <link rel="stylesheet" href="assets/css/index.css" />
    <title>Bienvenue</title>
</head>
<body>
    <header>
        <h1>Produits</h1>
    </header>
    
    <div class="products-container">
        <?php foreach ($products as $product) { ?>
            <div class="product-item">
                <div class="product-cover">
                    <img src="<?php echo $product['image']; ?>" alt="<?php echo $product['name']; ?>" />
                </div>
                <div class="product-infos">
                    <h2><?php echo $product['name']; ?></h2>
                    <div class="product-stars">
                        *****
                    </div>
                    <h3><?php echo $product['price']; ?> €</h3>
                </div>
            </div>
        <?php } ?>
    </div>
</body>
</html>